# Generated by Django 5.1.3 on 2025-01-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='date_сreated',
            new_name='date_created',
        ),
    ]
