# Generated by Django 5.1.3 on 2025-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_rename_date_biography_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='biography',
            name='h1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='biography',
            name='header',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
