from typing import Protocol, List




class BaseServiceProtocol(Protocol):
    def get_all(self) -> List: ...

    def create(self, data) -> None: ...

    def update(self, data) -> None: ...

    def delete(self, model_id: int) -> None: ...

    def getby(self, **filters: dict) -> List: ...