# Generated by Django 5.1.4 on 2024-12-18 09:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'actual tag',
                'verbose_name_plural': 'actual tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('header', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=100)),
                ('main_photo', models.TextField(blank=True)),
                ('content', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_tags', models.ManyToManyField(blank=True, to='actual.actualtag')),
            ],
            options={
                'verbose_name': 'actual',
                'verbose_name_plural': 'actual',
                'ordering': ['-date_created'],
            },
        ),
    ]
