# Generated by Django 5.1.5 on 2025-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
