# Generated by Django 5.1.4 on 2025-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='date_created',
            field=models.DateField(),
        ),
    ]
