# Generated by Django 5.1.3 on 2025-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='actual_tags',
            field=models.CharField(max_length=100),
        ),
    ]
