# Generated by Django 5.1.4 on 2025-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='actual_tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actual',
            name='description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='actual',
            name='h1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='actual',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
