# Generated by Django 5.1.4 on 2025-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0002_alter_actual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
