# Generated by Django 5.1.5 on 2025-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0003_alter_actual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='slug',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
