# Generated by Django 5.1.5 on 2025-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual', '0004_alter_actual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actual',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
