# Generated by Django 5.1.5 on 2025-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='on_website',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
