# Generated by Django 5.1.4 on 2025-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='h1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
