# Generated by Django 5.1.4 on 2025-01-27 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='h1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='location',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='official_response',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='on_website',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='photos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
