# Generated by Django 5.1.4 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='official_response',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
