# Generated by Django 5.1.4 on 2025-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_description_alter_appeal_h1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='header',
        ),
    ]
