# Generated by Django 5.1.4 on 2025-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_alter_appeal_official_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='photos',
            field=models.FileField(blank=True, max_length=200, upload_to=''),
        ),
    ]
