# Generated by Django 5.1.4 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeal_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='photos',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
