# Generated by Django 5.1.4 on 2025-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_tags',
            field=models.CharField(max_length=100),
        ),
    ]
