# Generated by Django 5.1.4 on 2025-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='media',
            name='h1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
