# Generated by Django 5.1.4 on 2024-12-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='username',
        ),
    ]
