# Generated by Django 5.1.4 on 2024-12-05 09:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'actual tag',
                'verbose_name_plural': 'actual tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'media tag',
                'verbose_name_plural': 'media tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('header', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=100)),
                ('main_photo', models.TextField(blank=True)),
                ('content', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_tags', models.ManyToManyField(blank=True, related_name='actual', to='pages.actualtag')),
            ],
            options={
                'verbose_name': 'actual',
                'verbose_name_plural': 'actual',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('on_website', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('photos', models.CharField(blank=True, max_length=255, null=True)),
                ('official_response', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ManyToManyField(blank=True, to='pages.category')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('header', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=100)),
                ('main_photo', models.TextField(blank=True)),
                ('content', models.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_tags', models.ManyToManyField(blank=True, to='pages.mediatag')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ['-date_created'],
            },
        ),
    ]
