# Generated by Django 5.1.3 on 2024-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='писька')),
                ('media', models.FileField(upload_to='media', verbose_name='медиа')),
            ],
        ),
    ]
