# Generated by Django 5.1.3 on 2024-11-15 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160)),
                ('header', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media_images/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Медиа статья',
                'verbose_name_plural': 'Медиа статьи',
                'ordering': ['-date_created'],
            },
        ),
    ]
