# Generated by Django 5.1.3 on 2024-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date_created',
            field=models.DateField(),
        ),
    ]
