# Generated by Django 5.1.3 on 2024-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
