# Generated by Django 5.1.3 on 2024-11-15 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_actual_alter_media_options_alter_media_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.TextField(verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='media',
            name='header',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='media_images/', verbose_name='фото'),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='точка на карте')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё]+$')], verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё]+$')], verbose_name='имя')),
                ('patronymic', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё]+$')], verbose_name='отчество')),
                ('phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\+375\\d{9}$')], verbose_name='телефон')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='дата')),
                ('text', models.TextField(validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё.,!?;:()\\- ]+$')], verbose_name='текст обращения')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='appeal_photos/', verbose_name='фото')),
                ('status', models.CharField(choices=[('PENDING', 'Принято в работу'), ('COMPLETED', 'Исполнено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='статус')),
                ('on_website', models.BooleanField(default=False, verbose_name='присутсвие на сайте')),
                ('official_response', models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё.,!?;:()\\- ]+$')], verbose_name='официальный ответ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.category')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-date'],
            },
        ),
    ]
