# Generated by Django 5.1.3 on 2024-12-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_media_main_photo_media_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='main_photo',
        ),
    ]
